//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETKOplata.DataBaseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardStudent()
        {
            this.InputPrice = new HashSet<InputPrice>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public int IdGroup { get; set; }
        public int IdObshejit { get; set; }
        public int IdKatPlat { get; set; }
        public Nullable<System.DateTime> YearStar { get; set; }
        public Nullable<System.DateTime> YearFinal { get; set; }
        public Nullable<int> Otchis { get; set; }
        public string Note { get; set; }
        public Nullable<int> Room { get; set; }
        public string Image { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual KatPlat KatPlat { get; set; }
        public virtual PriceLife PriceLife { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputPrice> InputPrice { get; set; }
    }
}
