//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETKOplata.DataBaseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputPrice
    {
        public int Id { get; set; }
        public System.DateTime DatePrice { get; set; }
        public int NumberDoc { get; set; }
        public int SumPrice { get; set; }
        public string Note { get; set; }
        public int IdCardStudent { get; set; }
        public Nullable<int> Lgota { get; set; }
    
        public virtual CardStudent CardStudent { get; set; }
    }
}
