//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETKOplata.DataBaseApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OplataNETKEntities : DbContext
    {
        public OplataNETKEntities()
            : base("name=OplataNETKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardStudent> CardStudent { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<InputPrice> InputPrice { get; set; }
        public virtual DbSet<KatPlat> KatPlat { get; set; }
        public virtual DbSet<PriceLife> PriceLife { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
